services:  

  #KAFKA
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_NUM_PARTITIONS: "1"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
      KAFKA_CFG_MIN_INSYNC_REPLICAS: "1"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_CFG_LOG_DIRS: /var/lib/kafka/data

    volumes:
        - kafka-data:/var/lib/kafka/dat

  # DATABASE
  database:
    image: postgres:latest
    container_name: pgsql-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${PGSQL_HOST_PORT}:5432
    volumes:
      - postgres_lvl_0_data:/var/lib/postgresql/data

  # Migration
  migration:
    image: migrate/migrate
    container_name: db-migrate
    environment:
      DB_URL: ${DB_URL}
    volumes:
      - ./database/migrations:/migrations
    entrypoint: >
      sh -c '
        sleep 5;
        migrate -path /migrations -database "$DB_URL" up
      '
    depends_on:
      - database


volumes:
  kafka-data:
  postgres_lvl_0_data:
