services:
  database:
    image: postgres:latest
    container_name: pgsql-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${PGSQL_HOST_PORT}:5432
    volumes:
      - postgres_lvl_0_data:/var/lib/postgresql/data
  migration:
    image: migrate/migrate
    container_name: db-migrate
    environment:
      DB_URL: ${DB_URL}
    volumes:
      - ../repository/migrations:/migrations
    entrypoint: >
      sh -c '
        sleep 5;
        migrate -path /migrations -database "$DB_URL" up
      '
    depends_on:
      - database



volumes:
  postgres_lvl_0_data: